//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _mvc_crud_app_1.DB_Context_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_regitration
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public long mobile { get; set; }
    }
}
